<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageId>asdfDEV.Rowdy</PackageId>
    <Authors>ShawnSeanShaun</Authors>
    <Company>asdfDEV</Company>
    <PackageDescription>Lightweight HTTP mock server.

    This package has been designed using resources from Flaticon.com
    </PackageDescription>
    <RepositoryUrl>https://github.com/ShawnTheBeachy/rowdy</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageProjectUrl>https://github.com/ShawnTheBeachy/rowdy</PackageProjectUrl>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <PackageTags>.net;http;</PackageTags>
    <PackageIcon>assets/nuget-package-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="TUnit.Assertions" Version="1.33.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\assets\nuget-package-icon.png">
      <Link>.nuget\%(FileName)%(Extension)</Link>
      <Pack>true</Pack>
      <PackagePath>/assets/nuget-package-icon.png</PackagePath>
    </Content>
    <Content Include="..\..\README.md">
      <Link>.nuget\%(FileName)%(Extension)</Link>
      <Pack>true</Pack>
      <PackagePath>README.md</PackagePath>
    </Content>
  </ItemGroup>

  <Target
    Name="Husky"
    AfterTargets="Restore"
    Condition="'$(HUSKY)' != 0 and '$(IsCrossTargetingBuild)' == 'true'"
    Inputs="..\..\.config\dotnet-tools.json"
    Outputs="..\..\.husky\_\install.stamp"
  >
    <Exec
      Command="dotnet tool restore"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
    />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
      WorkingDirectory="..\.."
    />
    <Touch
      Files="..\..\.husky\_\install.stamp"
      AlwaysCreate="true"
      Condition="Exists('..\..\.husky\_')"
    />

    <ItemGroup>
      <FileWrites Include="..\..\.husky\_\install.stamp" />
    </ItemGroup>
  </Target>
</Project>
